"""Analysis helpers for experiment-specific diagnostics."""

from poregen.analysis.r03 import (
    AuxiliaryXCTDecoder,
    R03Runtime,
    build_patch_loader,
    charbonnier_on_sigmoid_logits,
    encode_mu,
    evaluate_auxiliary_decoder,
    find_transition_focus,
    flatten_mu,
    freeze_module,
    load_r03_runtime,
    local_mask_variance_map,
    mask_gradient_density,
    mask_local_variance_density,
    mean_latent_channels,
    samplewise_charbonnier,
    samplewise_sharpness_proxy,
    sigmoid_xct,
    transition_percentile_threshold,
    train_auxiliary_decoder,
)

__all__ = [
    "AuxiliaryXCTDecoder",
    "R03Runtime",
    "build_patch_loader",
    "charbonnier_on_sigmoid_logits",
    "encode_mu",
    "evaluate_auxiliary_decoder",
    "find_transition_focus",
    "flatten_mu",
    "freeze_module",
    "load_r03_runtime",
    "local_mask_variance_map",
    "mask_gradient_density",
    "mask_local_variance_density",
    "mean_latent_channels",
    "samplewise_charbonnier",
    "samplewise_sharpness_proxy",
    "sigmoid_xct",
    "transition_percentile_threshold",
    "train_auxiliary_decoder",
]
