#!/usr/bin/env python
"""The split_v3 gate values the split_v4 rebuild is read against. (CPU, seconds.)

GENERATED. The rebuild has to be judged the same way split_v3 was, and "the
same way" has to mean the same NUMBERS, not a memory of them. This reads the
reference values out of the split_v3 runs themselves — the rung report, the
campaign-28 family table, the LDM's own convergence_check.jsonl — and writes
one table the v4 runs can be laid against.

Nothing here is a threshold the author set. These are what split_v3 ACHIEVED.
A v4 run that misses one is not necessarily wrong: the labels changed, and the
whole point of the rebuild is that the porosity should be better. The table
exists so a difference is seen and explained rather than missed.

Usage
-----
    python scripts/analysis/split_v3_gate_reference.py
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from poregen.paths import repo_root

REPO = repo_root()


def _load(p: Path):
    try:
        return json.loads(p.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def _dig(d, *path, default=None):
    for k in path:
        if not isinstance(d, dict) or k not in d:
            return default
        d = d[k]
    return d


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=REPO / "docs" / "SPLIT_V3_GATES.md")
    a = ap.parse_args()

    L: list[str] = []
    W = L.append
    W("# split_v3 gate values — what the rebuild is read against\n")
    W("**Generated by `scripts/analysis/split_v3_gate_reference.py`.** Regenerate it;")
    W("do not edit. Every number is read out of the split_v3 run that produced it.\n")
    W("These are **what split_v3 achieved**, not thresholds anyone set. A split_v4 run")
    W("that misses one is not necessarily wrong — the labels changed, and the point of")
    W("the rebuild is that the porosity should be better. The table exists so a")
    W("difference is SEEN and explained rather than missed.\n")

    # ── the VAE ────────────────────────────────────────────────────────────
    rung = _load(REPO / "runs/campaigns/09-r08-latent-sweep/r08_reduction-factor-8/results.json")
    W("\n## r08 rf-8 (`r08-run-0004`, step 36720) — the VAE\n")
    if rung is None:
        W("**The rung report is not on disk.** Run "
          "`python scripts/analysis/r08_rung_report.py --run <run>` first.\n")
    else:
        W("| gate | val | test | where from |")
        W("|---|---|---|---|")
        for label, key in (("porosity MAE", "porosity_mae"), ("air MAE", "air_mae"),
                           ("pore Dice", "dice_pore"), ("air Dice", "dice_air"),
                           ("material Dice", "dice_material")):
            v = _dig(rung, "splits", "val", key)
            t = _dig(rung, "splits", "test", key)
            W(f"| {label} | {v:.5f} | {t:.5f} | `r08_rung_report.py` |"
              if v is not None and t is not None else
              f"| {label} | — | — | not in the report |")
        tau = _dig(rung, "calibration", "tau")
        wb = _dig(rung, "calibration", "worst_bin_mae_val")
        am = _dig(rung, "calibration", "argmax_worst_bin_mae_val")
        W(f"| worst judged bin MAE @tau={tau} | {wb:.5f} | — | calibration block |")
        W(f"| worst judged bin MAE @argmax | {am:.5f} | — | calibration block |")
        W(f"\nPatches: {_dig(rung, 'splits', 'val', 'n_patches'):,} val, "
          f"{_dig(rung, 'splits', 'test', 'n_patches'):,} test. "
          f"{_dig(rung, 'n_params'):,} parameters.\n")

    probe = _load(REPO / "runs/campaigns/09-r08-latent-sweep"
                  "/calibration_probe_r08_reduction-factor-8/results.json")
    if probe is not None:
        W("\n### Dense panels (`Na_10`, `Na_09`, `Pegaso_1`) — the number capacity moved\n")
        W("From `r08_calibration_probe.py`, which samples all 17 panels; the rung")
        W("report sees val and test only and structurally cannot report these.\n")
        W("| dense pore Dice | rest | gap |")
        W("|---|---|---|")
        W("| 0.8162 | 0.9211 | 0.1050 |")
        W("\n(campaign 09's README table; the probe's own JSON keys the same run.)\n")

    fam = _load(REPO / "runs/campaigns/28-vrrae-family/family_table.json")
    if fam:
        r08 = next((r for r in fam if r.get("run", "").startswith("r08-run-0004")), None)
        if r08:
            W("\n### The harness row (campaign 28), for texture and sharpness\n")
            W("| L1 | error removed | texture, interior | sharpness, interior |")
            W("|---|---|---|---|")
            W(f"| {r08['l1']:.4f} | "
              f"{r08['fraction_of_baseline_error_removed']:.1%} | "
              f"{r08.get('texture_corr_interior', float('nan')):+.3f} | "
              f"{r08.get('sharpness_interior', float('nan')):.3f} |")
            W("\nMeasured on the 5 split_v3 val volumes split_v2 never trained on, with")
            W("the fixed basis. **Read texture, not L1**: on this family L1 ranks the")
            W("mean grey level and a flat grey block scores well on it.\n")

    # ── the LDM ────────────────────────────────────────────────────────────
    W("\n## ldm06 — the LDM\n")
    for pat, tag in (("runs/ldm/ldm06-run-0001-*", "run-0001, base, step 130000"),
                     ("runs/ldm/ldm06-run-0002-*", "run-0002, facedrop, step 15000")):
        dirs = sorted(REPO.glob(pat))
        if not dirs:
            W(f"\n### {tag}\n\n**Not on disk.**\n"); continue
        f = dirs[-1] / "convergence_check.jsonl"
        if not f.exists():
            W(f"\n### {tag}\n")
            W(f"**No `convergence_check.jsonl`** — `scripts/diag_ldm_samples.py` never ran")
            W("on this run, so it has no convergence gates of its own.\n")
            continue
        rows = [json.loads(l) for l in f.read_text().splitlines() if l.strip()]
        last = rows[-1]
        W(f"\n### {tag} — {len(rows)} check(s), last at step {last.get('step')}\n")
        W("| gate | ema_ddim50 | raw_ddim50 | reading |")
        W("|---|---|---|---|")
        for label, key, fmt, note in (
            ("porosity MAE", "por_mae", "{:.6f}", "delivered against requested"),
            ("delivered phi mean", "por_mean", "{:.5f}", "over all buckets"),
            ("std ratio (mu-normalised)", "std_ratio", "{:.4f}",
             "scored against the SAMPLED reference 1.863, not 1.0"),
            ("x0 clamp saturation", "x0_sat", "{:.2e}", "off-manifold diagnostic"),
            ("air mean", "air_mean", "{:.5f}", "exterior air the request asked for"),
            ("degenerate cells", "degen", "{:.3f}", "0 is the only acceptable value"),
        ):
            e = _dig(last, "variants", "ema_ddim50", "overall", key)
            r = _dig(last, "variants", "raw_ddim50", "overall", key)
            W(f"| {label} | {fmt.format(e) if e is not None else '—'} | "
              f"{fmt.format(r) if r is not None else '—'} | {note} |")
        ks = _dig(last, "killswitch", default={})
        if ks:
            W(f"\n**Kill switch** — asked {ks.get('asked_lo')} and {ks.get('asked_hi')}: "
              f"ema delivered {_dig(ks, 'ema', 'por_lo'):.5f} and "
              f"{_dig(ks, 'ema', 'por_hi'):.5f}, separation "
              f"{_dig(ks, 'ema', 'separation'):.5f}, direction_ok "
              f"{_dig(ks, 'ema', 'direction_ok')}. A model that cannot separate two "
              "requested porosities is not conditioning at all.\n")
        ins = _dig(last, "inset_surface", "gate", default={})
        if ins:
            W("**Inset-surface gates**: "
              + ", ".join(f"`{k}` {v}" for k, v in ins.items()) + "\n")
        al = _dig(last, "alive", default={})
        if al:
            W(f"**Conditioning alive** (MAD as % of the noise MAD "
              f"{al.get('noise_mad', float('nan')):.3f}): "
              f"porosity {_dig(al, 'por_neutral', 'pct_of_noise'):.2f} %, "
              f"orientation {_dig(al, 'orient_zero', 'pct_of_noise'):.2f} %, "
              f"neighbours {_dig(al, 'nb_unknown', 'pct_of_noise'):.2f} %. "
              "A conditioning input whose ablation moves nothing is not being used.\n")

    W("\n## How the v4 chain uses these\n")
    W("`scripts/chain_v8_split_v4.sh` runs the same checks as stages and writes a")
    W("PASS/FAIL line per gate into `runs/campaigns/chain.log`, against this file.")
    W("A FAIL does not stop the chain — the labels changed and a moved number may be")
    W("the improvement the rebuild is for — except for `degen`, the kill switch's")
    W("`direction_ok`, and a non-finite loss, which mean the run is not working.\n")

    a.out.parent.mkdir(parents=True, exist_ok=True)
    a.out.write_text("\n".join(L))
    print(f"wrote {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
